---
- name: 'Find files and directories owned by test user and archive it'
  hosts: "*"
  tasks:
    - include_vars: myvars.yaml
    - name: "Find files and directories"
      shell: find "{{ local_src }}" -mtime +30 -user test
      register: output
      delegate_to: 127.0.0.1

    - name: "Print the find result"
      debug:
        var: output.stdout_lines | list
      
    - name: "zip output files"
      archive:
        path: "{{ file_path }}"
        dest: "{{ local_archive_dir }}/test_user.gz"
        format: gz
      vars:
        file_path: "{{ output.stdout_lines }}| list"
      delegate_to: 127.0.0.1
    